services:
  apache-wsrs:
    image: php:5.6-apache
    container_name: apache_module
    ports:
      - "5556:80"
    #network_mode: "host"
    volumes:
      - ./apache-module/src:/var/www/html
      - ./custom.conf:/etc/apache2/conf-enabled/custom.conf
    command: bash -c "chmod 777 /var/www/html/uploads && a2enmod rewrite && apache2-foreground"
    restart: always